try {
    const name = 'Math'

    const myError= new Error('Custom message')
}catch(err){
    console.log(err)
}